name: my_summary
version: 1.0.0+17
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  platform: ^3.1.0
  url_launcher: ^6.1.11
  flutter_screenutil: ^5.8.4
  firebase_core: ^1.17.0
  get: 4.6.5
  flutter_web_plugins: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  fonts: 
    - family: Robot
      fonts: 
        - asset: assets/fonts/Roboto-Regular.ttf
  uses-material-design: true

analyzer: 
  plugins: 
    - dart_code_metrics

dart_code_metrics: 
  metrics: 
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  anti-patterns: 
    - long-method
    - long-parameter-list
  metrics-exclude: 
    - test/**
  rules: 
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else

