// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJ_9JLilgwn4PzNrdSuBJSG1jUsDOsvg',
    appId: '1:245182579399:web:c9ce0fdc5c8925be4534e2',
    messagingSenderId: '245182579399',
    projectId: 'my-summary-85e3a',
    authDomain: 'my-summary-85e3a.firebaseapp.com',
    storageBucket: 'my-summary-85e3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeV_lURDVa2WBSKf4_YVs85HjGSNsoiM',
    appId: '1:245182579399:android:6914787c03e6b8b44534e2',
    messagingSenderId: '245182579399',
    projectId: 'my-summary-85e3a',
    storageBucket: 'my-summary-85e3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnfi3IL5hxokI3EecdgbCIuDv3XwSVawY',
    appId: '1:245182579399:ios:eb1e4416f19417d04534e2',
    messagingSenderId: '245182579399',
    projectId: 'my-summary-85e3a',
    storageBucket: 'my-summary-85e3a.appspot.com',
    iosClientId: '245182579399-h9m5e0uuu6m43ck0cedoecdjg80arieh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mySummary',
  );
}
